# Generated by Django 4.2.7 on 2023-11-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Text', 'Text')], default='Call', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CRM.contact')),
            ],
        ),
    ]
