# Generated by Django 4.2.7 on 2023-11-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_contact_created_on_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
